dependencies {
    api project(':core:catalog:entities')
    api project(':core:identity:entities')
    api project(':core:catalog:api')
    api 'io.projectreactor:reactor-core'
    implementation 'org.springframework.boot:spring-boot-starter-data-neo4j'
    implementation "org.mapstruct:mapstruct:${rootProject.ext.mapStructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${rootProject.ext.mapStructVersion}"
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${rootProject.ext.lombokMapstructBindingVersion}"
    testAnnotationProcessor "org.mapstruct:mapstruct-processor:${rootProject.ext.mapStructVersion}"
}
